version: '3.8'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    depends_on:
      - postgres_db
    environment:
      POSTGRES_HOST: postgres_db
    ports:
      - 8001:8001

  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432